-- SELECT * FROM users u
-- FULL JOIN subscriptions s ON s.user_id = u.id
-- FULL JOIN videos v ON s.video_id = v.video_id
-- FULL JOIN auditions a ON a.user_id = u.id
-- FULL JOIN connections c ON c.user_id = u.id
-- FULL JOIN theaters t ON t.theater_id = c.theater_id
-- WHERE u.id = $1;